Merge routes in Router::Route
Flowneee/okapi-operation pull request #12
Opened 2023-09-27 12:39 UTC by slinkydeveloper

Fix #11

2023-10-12 13:10 UTC, slinkydeveloper commented
@Flowneee

2023-10-24 07:43 UTC, slinkydeveloper commented
Added the changelog, also for #13 :)

2023-10-31 18:11 UTC, Flowneee requested changes

2023-10-31 18:11 UTC, Flowneee commented on okapi-operation/CHANGELOG.md
> +## [0.2.1] - 2023-05-09
mark this as `[Unreleased]` for now pls, rest is LGTM

2023-11-29 11:08 UTC, slinkydeveloper commented
Hey, any chance we can merge and release this?

2023-12-03 13:47 UTC, merged